spring:
  application.name: recommendations

server:
  port: 8081

security:
  basic.enabled: false

endpoints.health.sensitive: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    hostname: theone